"""add notifications table

Revision ID: 7dab9305f281
Revises: 
Create Date: 2026-04-11 13:45:50.371355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dab9305f281'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('recipient_address', sa.String(length=254), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_idempotency', 'notifications', ['tenant_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_index('idx_notifications_status', 'notifications', ['status'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_index('idx_notifications_tenant', 'notifications', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notifications_tenant', table_name='notifications')
    op.drop_index('idx_notifications_status', table_name='notifications', postgresql_where=sa.text("status = 'queued'"))
    op.drop_index('idx_notifications_idempotency', table_name='notifications', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_table('notifications')
    # ### end Alembic commands ###
